services:
  backend:
    
    build : .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
       
    volumes:
     - .:/app/
    ports:
     - 9000:80
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    # device_requests:
    #   - driver: nvidia
    #     count: all
    #     capabilities: [gpu]
  master:
    image: locustio/locust
    ports:
     - "9200:8089"

    
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://backend:80
  
  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
    environment:
      LOCUST_WORKERS: 3
  celery:
    build: .
    container_name: celery_worker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
       
    volumes:
      - .:/app
    command: celery -A celery_worker.app worker --concurrency 8 --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis_broker
    ports:
      - "6379:6379"
volumes:
  .: