services:
  backend:
    
    image : whisper-api:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
     - .:/app/
    ports:
     - 9000:80
volumes:
  .: