services:
  backend:
    
    build : .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
       
    volumes:
     - .:/app/
    ports:
     - 9200:80
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    # device_requests:
    #   - driver: nvidia
    #     count: all
    #     capabilities: [gpu]
  master:
    image: locustio/locust
    ports:
     - "18767:9089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://backend:80
  
  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
volumes:
  .: